[proposal] development mode
Ogeon/rust-wiringpi pull request #13
Opened 2017-08-02 13:50 UTC by nisshiee

## Motivation

I usually write codes using Macbook. So I want to develop RPi project with Macbook.
But my project using `rust-wringpi` can't be compiled because original `wiringpi` doesn't support macOS. I think it's nice if it can at least be compiled.

## Proposal

New feature `development`.
It replace wiringpi bindings with dummy functions which only output simple logs.

In a cargo project using `rust-wiringpi`, we can switch mode.

- On RPi:

  ```
  cargo build
  cargo run
  ```

  These commands are same as current.

- On macbook:

  ```
  cargo build --features wiringpi/development
  cargo run --features wiringpi/development
  ```

  These commands

  - compile `rust-wiringpi` as rust native library
  - are available on macbook

2017-08-02 15:47 UTC, Ogeon commented
This is a great! It's something that has been missing for some time. I'll take a closer look later, but some things I came to think of now:

 * Can the macros include the "real" bindings? That would reduce duplication.

 * Can the macros be combined into one, as just two variants?

 * We might as well print the arguments for debug purposes.

 * The readme should contain a note about this feature and Travis should test build, docs and examples with it.

2017-08-03 01:14 UTC, nisshiee commented
Thank you for your replying. I will try these.

I have one question.

> Can the macros include the "real" bindings? That would reduce duplication.

Do you imagine like following code?

```rust
```

2017-08-03 06:32 UTC, Ogeon commented
Yes, that's what I had in mind.

2017-08-06 06:04 UTC, nisshiee commented
I use this revision in my project for a few days. There are no problems.

@Ogeon review plz 😄

2017-08-08 09:10 UTC, Ogeon requested changes
Sorry for the wait! I was distracted by family.

I think the changes looks great :+1:, but there are still a few details left to improve.

2017-08-08 09:10 UTC, Ogeon commented on README.md
> +With this mode, you can build and debug your project on wiringpi-not-supported platform such as macOS.
Just a bit of grammar touch-up and rephrasing suggestion:

```
In development mode, `rust-wiringpi` is compiled as a rust-native library excluding the original WiringPi.
And binding functions are replaced by dummy functions that output simple logs to stdout.
With this mode, you can build and debug your project on platforms that does not support WiringPi.
```

I don't think there is any reason to mention any specific OS :)

2017-08-08 09:10 UTC, Ogeon commented on README.md
> +...
Very nice!

2017-08-08 09:10 UTC, Ogeon commented on src/bindings.rs
> +}
I think the items in this block are unused. In that case you may just as well remove them, if you want to.

2017-08-08 09:10 UTC, Ogeon commented on .travis.yml
> +  - ./cross64 "build -v --features development"
This should be `cargo build ...` if we are testing it on the host platform.

2017-08-08 09:11 UTC, Ogeon commented on .travis.yml
> +  - ./cross64 "build -v --features development"
Oh, and maybe build the example as well.

2017-08-11 08:25 UTC, nisshiee commented on src/bindings.rs
> +}
Ok, I will remove them

2017-08-11 08:26 UTC, nisshiee commented on README.md
> +With this mode, you can build and debug your project on wiringpi-not-supported platform such as macOS.
Thank you for your advise!

2017-08-11 11:05 UTC, Ogeon approved these changes

2017-08-11 11:06 UTC, Ogeon commented
Great! Do you want to squash your commits? Otherwise I'll do it when merging.

2017-08-14 08:49 UTC, nisshiee commented
Sorry for being late.
I squashed my commits.

2017-08-14 09:13 UTC, Ogeon commented
No problem! Thank you! I'll make a release as soon as possible.

2017-08-14 09:13 UTC, merged